### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by yanis7774** [decentraland/sdk-issues#2] opened 2018-07-12 19:51 UTC
@nearnshaw 

```
<entity id="floor_1" position={{x: 0 , y: 0 , z: 0}} >

       <plane position={{x: 10 , y: 0 , z: 0}} scale={10} rotation={{x: 90 , y: 0 , z: 0}} material="#floor1" >
       <plane position={{x: 10 , y: 1 , z: 0}} scale={1} rotation={{x: 0 , y: 0 , z: 0}} material="#floor1" >
       
</entity>
```
but planes complitetly in different places.
and when I set scale 10 on second plane, its become huge. first one is small with 10 scale

<img width="1435" alt="sc1" src="https://user-images.githubusercontent.com/34626980/42655884-1a3323b2-8626-11e8-8ccf-747201ec392c.png">
<img width="1428" alt="sc2" src="https://user-images.githubusercontent.com/34626980/42655893-21ca60ea-8626-11e8-8f53-39d7fa3551b9.png">

**Comment by nearnshaw** [comment] 2018-07-15 14:04
Hi Yannis,

That is a very weird error indeed, but I haven't been able to reproduce it.
You have a syntax error with the XML, the error is probably related to
that, but in my case it doesn't let me run a preview at all.

The XML tags for the planes in the example are missing a closing / at the
end.

<entity id="floor_1" position={{x: 0 , y: 0 , z: 0}} >

<plane position={{x: 10 , y: 0 , z: 0}} scale={10} rotation={{x: 90 , y: 0
, z: 0}} material="#floor1" />
<plane position={{x: 10 , y: 1 , z: 0}} scale={1} rotation={{x: 0 , y: 0 ,
z: 0}} material="#floor1" />

</entity>

Make sure you're using the latest version of the SDK, maybe the fact that
it allowed you to run it with errors is because you're using an older
version.

Cheers,
Nico

**Comment by yanis7774** [comment] 2018-07-16 12:37
@nearnshaw thanks. I updated api version,  and it's okay now. And yes,  my fault with syntax.

**Closed as completed** 2018-07-18 18:45 UTC
